# Service accounts for your workloads
apiVersion: v1
kind: Namespace
metadata:
  name: app-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-a-sa
  namespace: app-a
  labels:
    azure.workload.identity/use: "true"
  annotations:
    # clientId of id-workload-a (access to Service Bus A).
    azure.workload.identity/client-id: "<WORKLOAD_A_CLIENT_ID>"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-b-sa
  namespace: app-b
  labels:
    azure.workload.identity/use: "true"
  annotations:
    # clientId of id-workload-b (access to Service Bus B).
    azure.workload.identity/client-id: "<WORKLOAD_B_CLIENT_ID>"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-c
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-c-sa
  namespace: app-c
  labels:
    azure.workload.identity/use: "true"
  annotations:
    # clientId of id-workload-c (access to Service Bus C).
    azure.workload.identity/client-id: "<WORKLOAD_C_CLIENT_ID>"
